# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tw56JaStIYaT3cC0dMgBI_w6LCizYwNb
"""

print(welcome_student("Stella"))

print(perimeter_of_square(5))

print(area_of_circle(5))

print(area_of_triangle(10,5))

find_hypotenuse(3, 4)

print(calculate_simple_interest(1000, 5, 2))

print(average_of_three(3, 6, 9))

print(calculate_power(2,3))

print(simplify_fraction(8, 14))

print(celsius_to_fahrenheit(0))

print(feet_to_meters(20))

print(find_percentage(35,40))

print(find_slope(1, 3, 2, 4))

print(find_distance(0, 0, 3, 4))

print(is_even(4))

print(is_prime(7))

print(is_solution(3, 2))  # True
print(is_solution(2, 2))  # False